
import type { Metadata } from 'next'
import { Inter, Nunito_Sans } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'
import AuthProvider from './context/AuthProvider'
import QueryProvider from './context/QueryProvider'
import HubProvider from './context/HubProvider'
import Header from '@/components/Header'
import { options } from './api/auth/[...nextauth]/options'



const inter = Nunito_Sans({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Trang Chủ - Web DQ',
  description: 'Generated by create next app',
  // icons: {
  //   icon: "",
  //   apple: "",
  // }
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider >
          <HubProvider>
            <QueryProvider>
              <Header />
              {children}
              <Footer />
            </QueryProvider>
          </HubProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
